rvm:
  - 1.9.3
notifications:
  recipients:
    - jarmo.p@gmail.com
before_script:
  - support/travis.sh
env:
  - WATIR_WEBDRIVER_BROWSER=internet_explorer
matrix:
  allow_failures:
    - rvm: ruby-head
